import { existsSync } from 'node:fs';

/**
 * The share card for a page, generated by `scripts/og-card.mjs` and committed
 * under `public/og/`.
 *
 * Cards are committed rather than built, so a new post can reach `main` with no
 * card of its own. This throws when that happens instead of shipping a page
 * whose `og:image` is a 404, which nothing else would catch: the four gates do
 * not fetch the tags they emit, and a scraper only fails much later, in someone
 * else's chat window.
 */
export function shareCard(name: string): string {
  const url = `/og/${name}.jpg`;

  if (!existsSync(`public${url}`)) {
    throw new Error(
      `No share card at ${url}. Run \`node scripts/og-card.mjs\` and commit what it writes.`
    );
  }

  return url;
}
